/*
 * ErrorCode
 * @author Severin Toldo
 * */
export enum ErrorCode {
    UNKNOWN = 'UNKNOWN',
    FTP_CONNECTION_FAILED = 'FTP_CONNECTION_FAILED',
    UPLOAD_FAILED = 'UPLOAD_FAILED',
    DOWNLOAD_FAILED = 'DOWNLOAD_FAILED',
    FETCHING_LIST_FAILED = 'FETCHING_LIST_FAILED',
    DELETE_FAILED = 'FETCHING_LIST_FAILED',
    FILES_NOT_THE_SAME = 'FILES_NOT_THE_SAME',
    SENDING_EMAIL_FAILED = 'SENDING_EMAIL_FAILED',
    FILE_EXCEEDS_ALLOWED_ATTACHMENT_SIZE = 'FILE_EXCEEDS_ATTACHMENT_SIZE'
}
